import { getNodeDefinition } from "./nodeRegistry.js";
import { validateGraph } from "./validation.js";

const safeName = value => `v_${String(value).replace(/[^A-Za-z0-9_]/g, "_")}`;
const quote = value => JSON.stringify(value);

const runtimePrelude = id => [
  "# Generated by Shulkr Flow Builder", `# automation: ${id}`, "import json", "import time", "import minescript as ms", "from shulkr import pathfinding", "",
  "cancelled = False", "MAX_STEPS = 10000", "_steps = 0", "",
  "def request_cancel():", "    global cancelled", "    cancelled = True", "",
  "def check_cancelled():", "    global _steps", "    _steps += 1", "    if cancelled: raise RuntimeError('Automation cancelled')", "    if _steps > MAX_STEPS: raise RuntimeError('Execution step limit exceeded')", "",
  "def report_node(node_id):", "    check_cancelled()", "    ms.echo_json(json.dumps({'event': 'flow.node', 'nodeId': node_id, 'at': time.time()}))", "",
  "def wait_seconds(seconds, node_id):", "    deadline = time.time() + seconds", "    while time.time() < deadline:", "        check_cancelled()", "        time.sleep(min(0.05, max(0, deadline - time.time())))", "",
  "def wait_for_path(target, timeout, node_id):", "    if target is None: raise RuntimeError('Target is missing at ' + node_id)", "    if not pathfinding.goto(*target): raise RuntimeError('Destination is unreachable at ' + node_id)", "    deadline = time.time() + timeout", "    while time.time() < deadline:", "        check_cancelled()", "        state = pathfinding.status()", "        if state.get('status') == 'arrived': return", "        if state.get('status', '').startswith('error') or state.get('status') == 'unreachable': raise RuntimeError('Destination is unreachable at ' + node_id)", "        time.sleep(0.05)", "    pathfinding.stop()", "    raise TimeoutError('Movement timed out at ' + node_id)", "",
  "def find_nearest_block(block_id, radius):", "    px, py, pz = map(round, ms.player_position())", "    for distance in range(int(radius) + 1):", "        for x in range(px-distance, px+distance+1):", "            for y in range(py-distance, py+distance+1):", "                for z in range(pz-distance, pz+distance+1):", "                    if ms.getblock(x, y, z) == block_id: return (x, y, z)", "        check_cancelled()", "    return None", "",
  "def mine_target(target, timeout, retries, node_id):", "    if target is None: raise RuntimeError('Target is missing at ' + node_id)", "    for attempt in range(int(retries) + 1):", "        check_cancelled()", "        ms.player_look_at(*target)", "        ms.player_press_attack(True)", "        try: wait_seconds(min(timeout, 1.0), node_id)", "        finally: ms.player_press_attack(False)", "        if ms.getblock(*target).endswith(':air') or ms.getblock(*target) in ('air', 'cave_air', 'void_air'): return", "    raise RuntimeError('Mine retries exhausted at ' + node_id)", "",
  "def cleanup():", "    pathfinding.stop()", "    ms.player_press_attack(False)", "",
  "try:", `    report_node(${quote("automation:" + id)})`
];

export function compileGraph(graph) {
  try {
    const validation = validateGraph(graph);
    const errors = validation.issues.filter(item => item.severity === "error").map(item => ({ ...item }));
    const warnings = validation.issues.filter(item => item.severity === "warning").map(item => ({ ...item }));
    const sourceMap = {};
    if (errors.length) return { code: "", errors, warnings, sourceMap };
    const lines = runtimePrelude(graph.id);
    const nodes = new Map(graph.nodes.map(node => [node.id, node]));
    const outgoing = node => graph.edges.filter(edge => edge.source === node.id && edge.dataType === "execution");
    const dataInputs = node => graph.edges.filter(edge => edge.target === node.id && edge.dataType !== "execution");
    const values = new Map();
    const emitted = new Set();
    let branchCounter = 0;
    const valueFor = (nodeId, handle) => values.get(`${nodeId}:${handle}`) || safeName(`${nodeId}_${handle}`);
    const emitNode = (node, indent = "    ") => {
      if (!node || emitted.has(node.id)) return;
      emitted.add(node.id);
      const definition = getNodeDefinition(node.type);
      const startLine = lines.length + 1;
      lines.push(`${indent}# node ${node.id}: ${definition.label}`, `${indent}report_node(${quote(node.id)})`);
      const incoming = dataInputs(node);
      for (const edge of incoming) values.set(`${node.id}:${edge.targetHandle}`, valueFor(edge.source, edge.sourceHandle));
      const data = node.data || {};
      switch (node.type) {
        case "flow.start": lines.push(`${indent}# execution entry`); break;
        case "flow.delay": lines.push(`${indent}wait_seconds(${Number(data.duration)}, ${quote(node.id)})`); break;
        case "flow.if": { const conditionEdge = incoming.find(edge => edge.targetHandle === "condition-in"); const condition = conditionEdge ? valueFor(node.id, "condition-in") : JSON.stringify(Boolean(data.condition)); lines.push(`${indent}if bool(${condition}):`); const branch = outgoing(node); const yes = nodes.get(branch.find(edge => edge.sourceHandle === "true-out")?.target); const no = nodes.get(branch.find(edge => edge.sourceHandle === "false-out")?.target); if (yes) emitNode(yes, indent + "    "); else lines.push(`${indent}    pass`); lines.push(`${indent}else:`); if (no) emitNode(no, indent + "    "); else lines.push(`${indent}    pass`); break; }
        case "flow.repeat": { const name = `_repeat_${branchCounter++}`; lines.push(`${indent}for ${name} in range(${Number(data.iterations)}):`, `${indent}    check_cancelled()`); const loop = nodes.get(outgoing(node).find(edge => edge.sourceHandle === "loop-out")?.target); if (loop) emitNode(loop, indent + "    "); break; }
        case "flow.stop": lines.push(`${indent}raise SystemExit()`); break;
        case "movement.walk_to_coordinates": { const c = data.coordinates; lines.push(`${indent}wait_for_path((${Number(c.x)}, ${Number(c.y)}, ${Number(c.z)}), ${Number(data.timeout)}, ${quote(node.id)})`); break; }
        case "movement.walk_to_target": lines.push(`${indent}wait_for_path(${valueFor(node.id, "target-in")}, ${Number(data.timeout)}, ${quote(node.id)})`); break;
        case "movement.stop": lines.push(`${indent}pathfinding.stop()`); break;
        case "world.find_nearest_block": { const name = safeName(node.id + "_target"); values.set(`${node.id}:target-out`, name); lines.push(`${indent}${name} = find_nearest_block(${quote(data.blockId)}, ${Number(data.radius)})`, `${indent}if ${name} is None: raise RuntimeError('Block not found at ' + ${quote(node.id)})`); break; }
        case "world.get_player_position": { const name = safeName(node.id + "_position"); values.set(`${node.id}:coordinates-out`, name); lines.push(`${indent}${name} = tuple(ms.player_position())`); break; }
        case "world.store_target": { const name = String(data.name || "target"); values.set(`${node.id}:target-out`, name); lines.push(`${indent}${name} = ${valueFor(node.id, "target-in")}`); break; }
        case "action.look_at_target": lines.push(`${indent}if ${valueFor(node.id, "target-in")} is None: raise RuntimeError('Target is missing at ' + ${quote(node.id)})`, `${indent}ms.player_look_at(*${valueFor(node.id, "target-in")})`); break;
        case "action.mine_block": lines.push(`${indent}mine_target(${valueFor(node.id, "target-in")}, ${Number(data.timeout)}, ${Number(data.retries)}, ${quote(node.id)})`); break;
        default: errors.push({ id: `compile:${node.id}`, severity: "error", code: "unsupported_node", nodeId: node.id, message: `Unsupported compiler node: ${node.type}.` }); return;
      }
      lines.push(`${indent}check_cancelled()`);
      sourceMap[node.id] = { startLine, endLine: lines.length };
      if (node.type !== "flow.if" && node.type !== "flow.repeat" && node.type !== "flow.stop") { const next = nodes.get(outgoing(node)[0]?.target); if (next) emitNode(next, indent); }
      if (node.type === "flow.repeat") { const done = nodes.get(outgoing(node).find(edge => edge.sourceHandle === "done-out")?.target); if (done) emitNode(done, indent); }
    };
    emitNode(graph.nodes.find(node => node.type === "flow.start"));
    lines.push("    ms.echo('Automation completed')", "except Exception as error:", "    ms.echo_json(json.dumps({'event': 'flow.error', 'error': str(error)}))", "    raise", "finally:", "    cleanup()", "");
    return { code: errors.length ? "" : lines.join("\n"), errors, warnings, sourceMap };
  } catch (error) {
    return { code: "", errors: [{ id: "compile:internal", severity: "error", code: "compile_internal", message: error instanceof Error ? error.message : String(error) }], warnings: [], sourceMap: {} };
  }
}
