export const DATA_TYPES = Object.freeze(["execution","number","text","boolean","coordinates","block","entity","target","item","variable","any"]);
const p=(id,label,dataType,options={})=>Object.freeze({id,label,dataType,required:false,multiple:false,...options});
const f=(key,label,type,defaultValue,options={})=>Object.freeze({key,label,type,defaultValue,required:false,...options});
const issue=(node,code,message)=>({id:`${node.id}:${code}`,severity:"error",nodeId:node.id,code,message});
const numberRules=(node,fields)=>fields.flatMap(([key,label,min,max])=>{const value=Number(node.data[key]);return !Number.isFinite(value)?[issue(node,`invalid_${key}`,`${label} must be a number.`)]:value<min||value>max?[issue(node,`invalid_${key}`,`${label} must be between ${min} and ${max}.`)]:[];});
const definition=value=>Object.freeze({version:1,description:"",colour:"#9d4dff",executionInputs:[],executionOutputs:[],dataInputs:[],dataOutputs:[],properties:[],defaultData:{},dangerous:false,allowSelfLoop:false,validate:()=>[],...value});

export const NODE_DEFINITIONS=Object.freeze([
 definition({type:"flow.start",label:"Start",category:"Flow",icon:"play",description:"Automation entry point.",executionOutputs:[p("execution-out","Execute","execution",{required:true})],createSummary:()=>"Entry point",validate:()=>[],compile:()=>["ms.echo('Automation started')"]}),
 definition({type:"flow.repeat",label:"Repeat",category:"Flow",icon:"repeat",description:"Repeat a branch with a safe bound.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("loop-out","Loop","execution",{required:true}),p("done-out","Done","execution")],properties:[f("iterations","Iterations","number",10,{required:true,min:1,max:10000,step:1})],defaultData:{iterations:10},createSummary:d=>`${d.iterations} iterations`,validate:n=>numberRules(n,[["iterations","Iterations",1,10000]]),compile:n=>[`# repeat limit: ${n.data.iterations}`]}),
 definition({type:"flow.delay",label:"Delay",category:"Flow",icon:"clock",description:"Yield for a duration.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution",{required:true})],properties:[f("duration","Duration","timeout",2,{required:true,min:.05,max:3600,step:.05})],defaultData:{duration:2},createSummary:d=>`${d.duration} seconds`,validate:n=>numberRules(n,[["duration","Duration",.05,3600]]),compile:n=>[`time.sleep(${Number(n.data.duration)})`]}),
 definition({type:"flow.if",label:"If",category:"Flow",icon:"code-branch",description:"Branch using a boolean input.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("true-out","True","execution",{required:true}),p("false-out","False","execution")],dataInputs:[p("condition-in","Condition","boolean")],properties:[f("condition","Condition","boolean",true,{required:true})],defaultData:{condition:true},createSummary:d=>`Condition: ${Boolean(d.condition)}`,validate:()=>[],compile:()=>[]}),
 definition({type:"flow.stop",label:"Stop",category:"Flow",icon:"stop",description:"Stop the automation.",executionInputs:[p("execution-in","Execute","execution",{required:true})],createSummary:()=>"End execution",validate:()=>[],compile:()=>["raise SystemExit()"]}),
 definition({type:"movement.walk_to_coordinates",label:"Walk To Coordinates",category:"Movement",icon:"person-walking",description:"Pathfind to fixed coordinates.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution",{required:true})],dataInputs:[p("coordinates-in","Coordinates","coordinates")],properties:[f("coordinates","Coordinates","coordinates",{x:0,y:64,z:0},{required:true}),f("timeout","Timeout","timeout",30,{required:true,min:1,max:300})],defaultData:{coordinates:{x:0,y:64,z:0},timeout:30},createSummary:d=>`${d.coordinates?.x??0}, ${d.coordinates?.y??0}, ${d.coordinates?.z??0}`,validate:n=>[...numberRules({id:n.id,data:{x:n.data.coordinates?.x,y:n.data.coordinates?.y,z:n.data.coordinates?.z}},[["x","X",-30000000,30000000],["y","Y",-2048,2048],["z","Z",-30000000,30000000]]),...numberRules(n,[["timeout","Timeout",1,300]])],compile:n=>{const c=n.data.coordinates;return [`movement = pathfinder.get('goto')(${c.x}, ${c.y}, ${c.z})`,`wait_for_path(movement, ${n.data.timeout}, ${JSON.stringify(n.id)})`];}}),
 definition({type:"movement.walk_to_target",label:"Walk To Target",category:"Movement",icon:"route",description:"Pathfind to the current target.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution",{required:true})],dataInputs:[p("target-in","Target","target",{required:true})],properties:[f("timeout","Timeout","timeout",30,{required:true,min:1,max:300})],defaultData:{timeout:30},createSummary:d=>`timeout ${d.timeout}s`,validate:n=>numberRules(n,[["timeout","Timeout",1,300]]),compile:n=>["if target is None: raise RuntimeError('Target is missing')","movement = pathfinder.get('goto')(*target)",`wait_for_path(movement, ${n.data.timeout}, ${JSON.stringify(n.id)})`]}),
 definition({type:"movement.stop",label:"Stop Movement",category:"Movement",icon:"hand",description:"Cancel active pathfinding.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution")],createSummary:()=>"Cancel path",validate:()=>[],compile:()=>["pathfinder.get('cancel')()"]}),
 definition({type:"world.find_nearest_block",label:"Find Nearest Block",category:"World",icon:"magnifying-glass",description:"Find a nearby block type.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution",{required:true})],dataOutputs:[p("target-out","Target","target")],properties:[f("blockId","Block ID","block","minecraft:oak_log",{required:true}),f("radius","Radius","number",32,{required:true,min:1,max:128})],defaultData:{blockId:"minecraft:oak_log",radius:32},createSummary:d=>`${String(d.blockId||"").replace("minecraft:","")} · radius ${d.radius}`,validate:n=>[...(!/^[a-z0-9_.-]+:[a-z0-9_./-]+$/.test(String(n.data.blockId))?[issue(n,"invalid_block","Block ID must use namespace:block format.")]:[]),...numberRules(n,[["radius","Radius",1,128]])],compile:n=>[`target = find_nearest_block(${JSON.stringify(n.data.blockId)}, ${n.data.radius})`,`if target is None: raise RuntimeError('Block not found')`]}),
 definition({type:"world.get_player_position",label:"Get Player Position",category:"World",icon:"location-dot",description:"Read the player coordinates.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution",{required:true})],dataOutputs:[p("coordinates-out","Coordinates","coordinates")],createSummary:()=>"Current position",validate:()=>[],compile:()=>["player_position = tuple(ms.player_position())"]}),
 definition({type:"world.store_target",label:"Store Target",category:"World",icon:"bookmark",description:"Store a target under a variable name.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution",{required:true})],dataInputs:[p("target-in","Target","target",{required:true})],dataOutputs:[p("target-out","Target","target")],properties:[f("name","Variable name","text","target",{required:true})],defaultData:{name:"target"},createSummary:d=>String(d.name||"target"),validate:n=>!/^[A-Za-z_][A-Za-z0-9_]*$/.test(String(n.data.name))?[issue(n,"invalid_variable","Variable name is invalid.")]:[],compile:n=>[`${n.data.name} = target`]}),
 definition({type:"action.look_at_target",label:"Look At Target",category:"Player Actions",icon:"eye",description:"Look towards a target.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution",{required:true})],dataInputs:[p("target-in","Target","target",{required:true})],createSummary:()=>"Current target",validate:()=>[],compile:()=>["if target is None: raise RuntimeError('Target is missing')","ms.player_look_at(*target)"]}),
 definition({type:"action.mine_block",label:"Mine Block",category:"Player Actions",icon:"hammer",description:"Mine the current target safely.",executionInputs:[p("execution-in","Execute","execution",{required:true})],executionOutputs:[p("execution-out","Execute","execution")],dataInputs:[p("target-in","Target","target",{required:true})],properties:[f("retries","Retries","retries",3,{required:true,min:0,max:10}),f("timeout","Timeout","timeout",15,{required:true,min:1,max:300})],defaultData:{retries:3,timeout:15},createSummary:d=>`${d.retries} retries · ${d.timeout}s`,validate:n=>numberRules(n,[["retries","Retries",0,10],["timeout","Timeout",1,300]]),dangerous:true,compile:n=>[`mine_target(target, ${n.data.timeout}, ${n.data.retries}, ${JSON.stringify(n.id)})`]})
]);
export const NODE_REGISTRY=new Map(NODE_DEFINITIONS.map(d=>[d.type,d]));
export const getNodeDefinition=type=>NODE_REGISTRY.get(type)||null;
export const defaultData=type=>structuredClone(getNodeDefinition(type)?.defaultData||{});
export function portsFor(definition){return [...definition.executionInputs,...definition.executionOutputs,...definition.dataInputs,...definition.dataOutputs];}
export function compatibleTypes(source,target){return source===target||source==="any"||target==="any"||(source==="block"&&target==="target")||(source==="entity"&&target==="target");}
