import{addEdge,addNode,createGraph,duplicateNodes,migrateGraph,removeSelection,updateNode}from"./graph.js";import{commit,createHistory,redo,undo}from"./history.js";import{compileGraph}from"./compiler.js";import{canConnect,validateGraph}from"./validation.js";import{cancelAutomationExecution,clearDraft,createAutomation,createAutomationFromTemplate,deleteAutomation,duplicateAutomation,executeAutomation,listAutomations,loadAutomation,loadAutomationExecution,loadDraft,publishAutomation,saveAutomation,saveDraft}from"./persistence.js";
const runtime=()=>({status:"disconnected",clientConnected:false,clientId:"",executionId:"",activeNodeId:null,logs:[],variables:{},message:"Minecraft client disconnected."});
export class FlowStore extends EventTarget{constructor(){super();this.api=null;this.userId="anonymous";this.state={graph:createGraph(),selectedNodeIds:[],selectedEdgeIds:[],dirty:false,saving:false,savedAt:null,baseUpdatedAt:null,error:"",automations:[],templates:[],loading:false,validation:null,compileResult:null,runtime:runtime(),history:null,clipboard:[],librarySearch:""};this.recalculate();this.state.history=createHistory(this.state.graph);}
 configure({api,userId}){const nextUserId=userId||"anonymous";if(this.userId!==nextUserId){clearTimeout(this.autosave);clearTimeout(this.viewportTimer);clearTimeout(this.recalculateTimer);clearTimeout(this.executionPoll);this.state={graph:createGraph(),selectedNodeIds:[],selectedEdgeIds:[],dirty:false,saving:false,savedAt:null,baseUpdatedAt:null,error:"",automations:[],templates:[],loading:false,validation:null,compileResult:null,runtime:runtime(),history:null,clipboard:[],librarySearch:""};this.recalculate();this.state.history=createHistory(this.state.graph);}this.api=typeof api==="function"?api:null;this.userId=nextUserId;}
 setClientConnection(connected,shouldEmit=true,clientId=""){const next=Boolean(connected),nextId=next?String(clientId||this.state.runtime.clientId||""):"";if(this.state.runtime.clientConnected===next&&this.state.runtime.clientId===nextId)return;const busy=["queued","running","cancelling"].includes(this.state.runtime.status);this.state.runtime={...this.state.runtime,clientConnected:next,clientId:nextId,status:busy?this.state.runtime.status:next?"ready":"disconnected",message:busy?this.state.runtime.message:next?"Minecraft client ready for automation execution.":"Minecraft client disconnected."};if(shouldEmit)this.emit();}
 snapshot(){return this.state;} emit(){this.dispatchEvent(new Event("change"));}
 recalculate(){this.state.validation=validateGraph(this.state.graph);this.state.compileResult=compileGraph(this.state.graph);}
 scheduleRecalculate(){clearTimeout(this.recalculateTimer);this.recalculateTimer=setTimeout(()=>{this.recalculate();this.emit();},60);}
 setGraph(graph,{dirty=false,history=true}={}){this.state.graph=migrateGraph(graph);this.state.dirty=dirty;this.state.baseUpdatedAt=this.state.graph.updatedAt||null;this.state.history=history?createHistory(this.state.graph):this.state.history;this.recalculate();this.emit();}
 edit(graph,{defer=false}={}){this.state.graph=graph;this.state.history=commit(this.state.history,graph);this.state.dirty=true;if(defer)this.scheduleRecalculate();else this.recalculate();this.queueAutosave();this.emit();}
 select(nodes=[],edges=[]){this.state.selectedNodeIds=nodes;this.state.selectedEdgeIds=edges;this.emit();}
 add(type,position){if(type==="flow.start"&&this.state.graph.nodes.some(n=>n.type===type))throw new Error("Only one Start node is allowed.");const next={x:Number(position?.x)||0,y:Number(position?.y)||0};while(this.state.graph.nodes.some(node=>Math.abs(node.position.x-next.x)<245&&Math.abs(node.position.y-next.y)<100)){next.x+=260;}this.edit(addNode(this.state.graph,type,next));this.select([this.state.graph.nodes.at(-1).id],[]);}
 addConnected(type,position,{source,sourceHandle,targetHandle}){if(type==="flow.start"&&this.state.graph.nodes.some(n=>n.type===type))throw new Error("Only one Start node is allowed.");const next={x:Number(position?.x)||0,y:Number(position?.y)||0};while(this.state.graph.nodes.some(node=>Math.abs(node.position.x-next.x)<245&&Math.abs(node.position.y-next.y)<100)){next.x+=260;}let graph=addNode(this.state.graph,type,next);const node=graph.nodes.at(-1),connection={source,sourceHandle,target:node.id,targetHandle},result=canConnect(graph,connection);if(!result.ok)throw new Error(result.message);graph=addEdge(graph,{...connection,dataType:result.dataType});this.edit(graph);this.select([node.id],[]);return node;}
 move(id,position){this.edit(updateNode(this.state.graph,id,{position}));}
 updateData(id,data){this.edit(updateNode(this.state.graph,id,{data}),{defer:true});}
 connect(connection){const result=canConnect(this.state.graph,connection);if(!result.ok)throw new Error(result.message);this.edit(addEdge(this.state.graph,{...connection,dataType:result.dataType}));}
 remove(){this.edit(removeSelection(this.state.graph,this.state.selectedNodeIds,this.state.selectedEdgeIds));this.select([],[]);}
 duplicate(){const allowed=this.state.selectedNodeIds.filter(id=>this.state.graph.nodes.find(node=>node.id===id)?.type!=="flow.start");if(!allowed.length)return;this.edit(duplicateNodes(this.state.graph,allowed));this.select(this.state.graph.nodes.slice(-allowed.length).map(n=>n.id),[]);}
 copy(){this.state.clipboard=this.state.graph.nodes.filter(n=>this.state.selectedNodeIds.includes(n.id)).map(node=>structuredClone(node));}
 paste(){const allowed=this.state.clipboard.filter(node=>node.type!=="flow.start"||!this.state.graph.nodes.some(existing=>existing.type==="flow.start"));if(!allowed.length)return;const graph={...this.state.graph,nodes:[...this.state.graph.nodes,...allowed.map(n=>({...structuredClone(n),id:`node-${crypto.randomUUID()}`,position:{x:n.position.x+40,y:n.position.y+40}}))]};this.edit(graph);this.select(graph.nodes.slice(-allowed.length).map(n=>n.id),[]);}
 undo(){if(!this.state.history.past.length)return;this.state.history=undo(this.state.history);this.state.graph=structuredClone(this.state.history.present);this.state.dirty=true;this.recalculate();this.emit();}
 redo(){if(!this.state.history.future.length)return;this.state.history=redo(this.state.history);this.state.graph=structuredClone(this.state.history.present);this.state.dirty=true;this.recalculate();this.emit();}
 setViewport(viewport){this.state.graph={...this.state.graph,viewport};this.state.dirty=true;clearTimeout(this.viewportTimer);this.viewportTimer=setTimeout(()=>{this.recalculate();this.queueAutosave();this.emit();},120);}
 rename(name){this.edit({...this.state.graph,name});}
 newGraph(){this.setGraph(createGraph(),{dirty:true});this.select([],[]);}
 async duplicateGraph(){if(this.api&&this.state.automations.some(graph=>graph.id===this.state.graph.id)){const copy=await duplicateAutomation(this.api,this.state.graph.id);this.state.automations.unshift(copy);this.setGraph(copy,{dirty:false});return copy;}const now=new Date().toISOString(),graph=structuredClone(this.state.graph);graph.id=`automation-${crypto.randomUUID()}`;graph.name=`${graph.name} Copy`;graph.createdAt=now;graph.updatedAt=now;this.setGraph(graph,{dirty:true});this.queueAutosave();return graph;}
 queueAutosave(){clearTimeout(this.autosave);this.autosave=setTimeout(()=>this.save().catch(error=>{this.state.error=error.message;this.emit();}),900);saveDraft(this.userId,this.state.graph);}
 async loadAll(){this.state.loading=true;this.emit();try{const list=await listAutomations(this.api);this.state.automations=list;this.state.error="";const draft=loadDraft(this.userId);if(draft)this.setGraph(draft,{dirty:true});else if(list[0])this.setGraph(list[0],{dirty:false});}catch(error){this.state.error=error.message;}finally{this.state.loading=false;this.emit();}}
 async retryLoad(){clearDraft(this.userId);this.state.error="";return this.loadAll();}
 async open(id){const graph=await loadAutomation(this.api,id);clearDraft(this.userId);this.setGraph(graph,{dirty:false});}
 async createFromTemplate(templateId,name){const graph=await createAutomationFromTemplate(this.api,templateId,name);this.state.automations.unshift(graph);this.setGraph(graph,{dirty:false});return graph;}
 async publish(metadata={}){if(!this.api)throw new Error("Not connected");if(!this.state.validation.valid)throw new Error("Fix validation errors before publishing");return publishAutomation(this.api,{...this.state.graph,generatedCode:this.state.compileResult.code},metadata);}
 async save(){if(!this.api||!this.state.dirty)return;this.state.saving=true;this.emit();try{const payload={...this.state.graph,generatedCode:this.state.compileResult.code};const existing=this.state.automations.some(graph=>graph.id===this.state.graph.id);const saved=existing?await saveAutomation(this.api,payload,this.state.baseUpdatedAt):await createAutomation(this.api,payload);this.state.graph=saved;this.state.baseUpdatedAt=saved.updatedAt;this.state.dirty=false;this.state.savedAt=new Date().toISOString();this.state.error="";clearDraft(this.userId);const i=this.state.automations.findIndex(g=>g.id===saved.id);if(i<0)this.state.automations.unshift(this.state.graph);else this.state.automations[i]=this.state.graph;}catch(error){this.state.error=error.message;throw error;}finally{this.state.saving=false;this.emit();}}
 applyExecution(execution){const status=String(execution?.status||"unknown"),messages=Array.isArray(execution?.logs)?execution.logs:[];this.state.runtime={...this.state.runtime,status,executionId:String(execution?.id||this.state.runtime.executionId||""),activeNodeId:execution?.activeNodeId||null,logs:messages,message:messages.at(-1)?.message||`Automation ${status}.`};this.emit();}
 async execute(confirmPermissions=false){if(!this.api)throw new Error("Not connected");if(!this.state.validation.valid)throw new Error("Fix validation errors before running");if(!this.state.runtime.clientConnected||!this.state.runtime.clientId)throw new Error("Connect a Minecraft client before running");if(this.state.dirty)await this.save();this.state.runtime={...this.state.runtime,status:"queued",message:"Queuing automation for Minecraft…",logs:[]};this.emit();const execution=await executeAutomation(this.api,this.state.graph.id,this.state.runtime.clientId,confirmPermissions);this.applyExecution(execution);this.pollExecution();return execution;}
 pollExecution(){clearTimeout(this.executionPoll);const id=this.state.runtime.executionId;if(!id)return;this.executionPoll=setTimeout(async()=>{try{const execution=await loadAutomationExecution(this.api,id);this.applyExecution(execution);if(["queued","running","cancelling"].includes(execution.status))this.pollExecution();}catch(error){this.state.runtime={...this.state.runtime,status:"unknown",message:error.message||"Execution status could not be refreshed."};this.emit();}},1000);}
 async cancelExecution(){const id=this.state.runtime.executionId;if(!id)return;const execution=await cancelAutomationExecution(this.api,id);this.applyExecution(execution);this.pollExecution();return execution;}
 async delete(){if(this.state.automations.some(graph=>graph.id===this.state.graph.id))await deleteAutomation(this.api,this.state.graph.id);clearDraft(this.userId);this.state.automations=this.state.automations.filter(g=>g.id!==this.state.graph.id);this.newGraph();}
}
export const flowStore=new FlowStore();
