import test from"node:test";import assert from"node:assert/strict";import{addEdge,createGraph,createNode,deserializeGraph,duplicateNodes,migrateGraph,serializeGraph}from"../src/flow/graph.js";import{compatibleTypes,defaultData,getNodeDefinition,NODE_DEFINITIONS}from"../src/flow/nodeRegistry.js";import{canConnect,validateGraph}from"../src/flow/validation.js";import{compileGraph}from"../src/flow/compiler.js";import{commit,createHistory,redo,undo}from"../src/flow/history.js";
const edge=(source,sourceHandle,target,targetHandle,dataType="execution")=>({id:`e-${Math.random()}`,source:source.id,sourceHandle,target:target.id,targetHandle,dataType});
function validGraph(){const graph=createGraph("Valid"),start=createNode("flow.start"),stop=createNode("flow.stop");graph.nodes=[start,stop];graph.edges=[edge(start,"execution-out",stop,"execution-in")];return graph;}
test("registry contains every required versioned definition",()=>{for(const type of["flow.start","flow.repeat","flow.delay","flow.if","flow.stop","movement.walk_to_coordinates","movement.walk_to_target","movement.stop","world.find_nearest_block","world.get_player_position","world.store_target","action.look_at_target","action.mine_block"]){const d=getNodeDefinition(type);assert.ok(d,type);assert.equal(d.version,1);assert.equal(typeof d.createSummary,"function");assert.equal(typeof d.validate,"function");}assert.equal(NODE_DEFINITIONS.length,13);});
test("default node creation deep-clones strictly typed data",()=>{const a=createNode("movement.walk_to_coordinates"),b=createNode("movement.walk_to_coordinates");a.data.coordinates.x=9;assert.equal(b.data.coordinates.x,0);assert.deepEqual(defaultData("action.mine_block"),{retries:3,timeout:15});});
test("connection rules accept compatible types and reject duplicates, occupied inputs, and self loops",()=>{const graph=createGraph(),find=createNode("world.find_nearest_block"),look=createNode("action.look_at_target");graph.nodes=[find,look];const c={source:find.id,sourceHandle:"target-out",target:look.id,targetHandle:"target-in"};assert.equal(canConnect(graph,c).ok,true);const connected=addEdge(graph,{...c,dataType:"target"});assert.match(canConnect(connected,c).message,/Duplicate|already/);assert.equal(canConnect(graph,{...c,target:find.id,targetHandle:"target-out"}).ok,false);assert.equal(compatibleTypes("block","target"),true);assert.equal(compatibleTypes("number","target"),false);});
test("validator detects missing and duplicate Start, unreachable nodes, properties and edge errors",()=>{const graph=createGraph(),a=createNode("flow.start"),b=createNode("flow.start"),block=createNode("world.find_nearest_block");block.data.blockId="bad id";graph.nodes=[a,b,block];graph.edges=[edge(a,"execution-out",block,"execution-in"),edge(a,"execution-out",block,"execution-in")];const codes=new Set(validateGraph(graph).issues.map(i=>i.code));for(const code of["multiple_starts","unreachable_node","invalid_block","duplicate_edge","missing_required_output"])assert.ok(codes.has(code),code);});
test("valid graph compiles with source maps, cancellation, and node IDs",()=>{const graph=validGraph(),result=compileGraph(graph);assert.equal(result.errors.length,0);assert.match(result.code,/if cancelled/);for(const node of graph.nodes){assert.match(result.code,new RegExp(node.id));assert.ok(result.sourceMap[node.id]);}});
test("unsupported compiler reports a mapped error",()=>{const graph=validGraph();graph.nodes[1]={...graph.nodes[1],type:"unknown.node"};const result=compileGraph(graph);assert.ok(result.errors.some(i=>i.nodeId===graph.nodes[1].id));assert.equal(result.code,"");});
test("validation diagnostics include stable IDs, severity, and suggested fixes",()=>{const graph=createGraph(),delay=createNode("flow.delay");graph.nodes=[delay];const result=validateGraph(graph),missing=result.issues.find(item=>item.code==="missing_start");assert.equal(result.valid,false);assert.equal(missing.id,"missing_start:graph");assert.equal(missing.severity,"error");assert.match(missing.suggestedFix,/Start/);});
test("conditional graph compiles deterministically",()=>{const graph=createGraph(),start=createNode("flow.start"),branch=createNode("flow.if"),stop=createNode("flow.stop");graph.nodes=[start,branch,stop];graph.edges=[edge(start,"execution-out",branch,"execution-in"),edge(branch,"true-out",stop,"execution-in")];const result=compileGraph(graph);assert.equal(result.errors.length,0);assert.match(result.code,/if bool\(true\)/);assert.ok(result.sourceMap[branch.id]);});
test("bounded repeat emits an iteration limit",()=>{const graph=createGraph(),start=createNode("flow.start"),repeat=createNode("flow.repeat"),stop=createNode("flow.stop");graph.nodes=[start,repeat,stop];graph.edges=[edge(start,"execution-out",repeat,"execution-in"),edge(repeat,"loop-out",stop,"execution-in")];const result=compileGraph(graph);assert.equal(result.errors.length,0);assert.match(result.code,/range\(10\)/);});
test("unsafe execution cycle is rejected",()=>{const graph=createGraph(),start=createNode("flow.start"),a=createNode("flow.delay"),b=createNode("flow.delay");graph.nodes=[start,a,b];graph.edges=[edge(start,"execution-out",a,"execution-in"),edge(a,"execution-out",b,"execution-in"),edge(b,"execution-out",a,"execution-in")];assert.ok(validateGraph(graph).issues.some(item=>item.code==="unsafe_execution_cycle"));assert.equal(compileGraph(graph).code,"");});
test("compiler includes timeout, retry, cancellation, cleanup, and verified APIs",()=>{const graph=createGraph(),start=createNode("flow.start"),find=createNode("world.find_nearest_block"),mine=createNode("action.mine_block"),stop=createNode("flow.stop");graph.nodes=[start,find,mine,stop];graph.edges=[edge(start,"execution-out",find,"execution-in"),edge(find,"execution-out",mine,"execution-in"),edge(find,"target-out",mine,"target-in","target"),edge(mine,"execution-out",stop,"execution-in")];const result=compileGraph(graph);assert.equal(result.errors.length,0);for(const text of["from shulkr import pathfinding","wait_for_path","MAX_STEPS","request_cancel","mine_target","retries","cleanup","player_press_attack","player_look_at"] )assert.match(result.code,new RegExp(text));});
test("serialization, deserialization and legacy migration preserve graph data",()=>{const graph=validGraph(),roundtrip=deserializeGraph(serializeGraph(graph));assert.deepEqual(roundtrip.nodes,graph.nodes);const legacy={...graph,nodes:[...graph.nodes,{...createNode("action.mine_block"),type:"player.mine_block",properties:{retryCount:2,timeout:9},data:undefined}],connections:graph.edges.map(e=>({id:e.id,fromNode:e.source,fromPort:"execute",toNode:e.target,toPort:"execute"})),edges:undefined};const migrated=migrateGraph(legacy);assert.equal(migrated.edges[0].sourceHandle,"execution-out");assert.equal(migrated.nodes[2].type,"action.mine_block");assert.equal(migrated.nodes[2].data.retries,2);assert.throws(()=>migrateGraph({...graph,formatVersion:99}),/Unsupported/);});
test("history undo/redo and copy-style duplication are immutable",()=>{const graph=validGraph();let history=createHistory(graph,10),changed={...graph,name:"Changed"};history=commit(history,changed);history=undo(history);assert.equal(history.present.name,"Valid");history=redo(history);assert.equal(history.present.name,"Changed");const copied=duplicateNodes(graph,[graph.nodes[0].id]);assert.equal(copied.nodes.length,3);assert.notEqual(copied.nodes[2].id,graph.nodes[0].id);});
test("formatted graph JSON reflects current metadata",()=>{const graph=validGraph();graph.name="Renamed";assert.match(serializeGraph(graph),/"Renamed"/);});
